### PR TITLE
Ejhumphrey 20160728 safefunc import

### PR DESCRIPTION
**Pull request by ejhumphrey**
tests pass locally, lessee what that punk travis has to say.

---
This change is [Reviewable](https://reviewable.io/reviews/bmcfee/pescador/27)

### CODE REVIEW

**Comment by bmcfee** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pescador/version.py, line 6 \[r1\]](https://reviewable.io:443/reviews/bmcfee/pescador/27#-KNm5NRZjHWDnj9NPn90:-KNm5NRZjHWDnj9NPn91:-1935618093) ([raw file](https://github.com/bmcfee/pescador/blob/d7134a9ff24a66b13f31aff2a7e9d97c06f5046a/pescador/version.py#L6)):*
> ```Python
> 
> short_version = '0.1'
> version = '0.1.3'
> ```

do version updates in a separate PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bmcfee/pescador/27)*

**Comment by ejhumphrey** [comment]
re: version bump, I don't totally understand the rationale, but /shrug

so my action items are:
- revert this version back to 0.1.2
- wait for green light on merge; then do it
- create another branch to bump the version, bump it, and PR it
- get green light and merge
- ...?
- profit

**Comment by bmcfee** [comment]
> p, I don't totally understand the rationale,

It's easier for sanity purposes if all release-related activities (changelog updates, version string updates, etc) are confined to the same PR.

**Comment by ejhumphrey** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pescador/version.py, line 6 \[r1\]](https://reviewable.io:443/reviews/bmcfee/pescador/27#-KNm5NRZjHWDnj9NPn90:-KNm6Shhvk1g2oAlizlY:-1124461552) ([raw file](https://github.com/bmcfee/pescador/blob/d7134a9ff24a66b13f31aff2a7e9d97c06f5046a/pescador/version.py#L6)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> do version updates in a separate PR
</details>
so for clarity, revert this change?

also, hi reviewable, nice to meet you and your shiny-if-non-obvious UI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bmcfee/pescador/27)*

**Comment by bmcfee** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pescador/version.py, line 6 \[r1\]](https://reviewable.io:443/reviews/bmcfee/pescador/27#-KNm5NRZjHWDnj9NPn90:-KNm7IMTOrfSXAs1VT_v:-645092616) ([raw file](https://github.com/bmcfee/pescador/blob/d7134a9ff24a66b13f31aff2a7e9d97c06f5046a/pescador/version.py#L6)):*
<details><summary><i>Previously, ejhumphrey (Eric J. Humphrey) wrote…</i></summary>
> so for clarity, revert this change?
> 
> also, hi reviewable, nice to meet you and your shiny-if-non-obvious UI
</details>
yes, revert plz

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bmcfee/pescador/27)*

**Comment by ejhumphrey** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pescador/version.py, line 6 \[r1\]](https://reviewable.io:443/reviews/bmcfee/pescador/27#-KNm5NRZjHWDnj9NPn90:-KNmATWf3KesUbTBY8cG:-919082076) ([raw file](https://github.com/bmcfee/pescador/blob/d7134a9ff24a66b13f31aff2a7e9d97c06f5046a/pescador/version.py#L6)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> yes, revert plz
</details>
kay done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bmcfee/pescador/27)*

**Comment by ejhumphrey** [comment]
kay we should be cool here once travis does it's thing. again.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bmcfee/pescador/27#-:-KNmAjLNRJCWR2b5AIg8:192767471)*

**Comment by cjacoby** [comment]
@bmcfee given the somewhat non-obviousness of the update protocol, perhaps it is worth adding a `CONTRIBUTING.md` that explains what to do to, or equivalent? 

A la https://github.com/librosa/librosa/blob/master/CONTRIBUTING.md

**Pull request merged**
